# Generated by Django 5.0.7 on 2024-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcecreamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('iname', models.CharField(max_length=200, verbose_name='Icecream Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Description')),
                ('price', models.IntegerField()),
                ('pic', models.FileField(upload_to='images/')),
            ],
        ),
    ]
