# Generated by Django 5.0.7 on 2024-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecreaminfo',
            name='det_desc',
            field=models.TextField(default=2, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
